# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    active: true
  PackageName:
    active: false
  NoWildcardImports:
    active: false

naming:
  PackageNaming:
    active: false

style:
  ForbiddenComment:
    active: false
  MagicNumber:
    active: false
  ReturnCount:
    active: false
  ThrowsCount:
    active: false
  WildcardImport:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
